version: 0.1
name: Guilds
main: com.windskull.GuildPlugin.GuildPluginMain
database: true
api-version: 1.14
depend: [SimpleORM]
softdepend: [WorldEdit, WorldGuard]
commands:
    guilds:
       description: Main command for guild plugin